version: "3.8"

services:
  app:
    volumes:
      - .:/app                # 👈 اربط المشروع كله
      - /app/node_modules     # 👈 علشان مايحصلش conflict بين node_modules بتوعك واللي جوة الكونتينر
    command: npx nodemon index.js
    environment:
      - NODE_ENV=development
    ports:
      - "8050:5000"
